name: flutter_midi_pro
description: The `flutter_midi_pro` plugin provides functions for loading SoundFont (.sf2) files, as well as playing and stopping MIDI notes.
version: 1.0.2
repository: https://github.com/MelihHakanPektas/flutter_midi_pro

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.14
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.melihhakanpektas.flutter_midi_pro
        pluginClass: FlutterMidiProPlugin
      ios:
        pluginClass: FlutterMidiProPlugin
      macos:
        pluginClass: FlutterMidiProPlugin
